{ config, lib, pkgs, ... }:

###############################################################################
# Audio visualizers.
#
#  * GLava — OpenGL spectrum that renders ON the desktop background (glassy,
#    GPU/compute-shader FFT). The showpiece. Runs via XWayland on Wayland
#    (auto-included; GLava is X11-first but works fine behind your windows).
#  * cava — lightweight terminal/ncurses bars. Great in a dropdown or a panel
#    widget; near-zero cost.
#
# Both read from PipeWire (your audio stack) automatically.
###############################################################################

{
  environment.systemPackages = with pkgs; [
    glava   # desktop-background OpenGL spectrum visualizer
    cava    # terminal spectrum (lightweight fallback / panel use)
  ];

  # NOTE on running GLava on the desktop background under KWin/Wayland:
  #   `glava --desktop` requests a desktop-layer window. On Plasma 6 Wayland this
  #   goes through XWayland; if it floats instead of sticking to the background,
  #   add a KWin window rule (System Settings → Window Management → Window Rules)
  #   to keep glava below + on all desktops. A starter config is generated by
  #   running `glava` once (writes ~/.config/glava/).
  #
  # cava just works: open a terminal, run `cava`. Themed by Stylix.
}
